### ISSUE TITLE
Build fails, non-resolvable parents

### ISSUE THREAD

**Issue by ermin-sakic** [geopet85/odlexample#1]
ermin@ermin-LIFEBOOK-E744:~/Desktop/odlexample$ mvn clean install 
[INFO] Scanning for projects...
Downloading: https://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/org/opendaylight/odlparent/odlparent/1.7.0-SNAPSHOT/maven-metadata.xml
Downloaded: https://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/org/opendaylight/odlparent/odlparent/1.7.0-SNAPSHOT/maven-metadata.xml (616 B at 0.4 KB/sec)
Downloading: https://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/org/opendaylight/odlparent/odlparent/1.7.0-SNAPSHOT/odlparent-1.7.0-20160531.105508-131.pom
Downloaded: https://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/org/opendaylight/odlparent/odlparent/1.7.0-SNAPSHOT/odlparent-1.7.0-20160531.105508-131.pom (55 KB at 51.1 KB/sec)
Downloading: https://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/org/opendaylight/odlparent/odlparent-lite/1.7.0-SNAPSHOT/maven-metadata.xml
Downloaded: https://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/org/opendaylight/odlparent/odlparent-lite/1.7.0-SNAPSHOT/maven-metadata.xml (834 B at 2.2 KB/sec)
Downloading: https://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/org/opendaylight/odlparent/odlparent-lite/1.7.0-SNAPSHOT/odlparent-lite-1.7.0-20160531.105510-131.pom
Downloaded: https://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/org/opendaylight/odlparent/odlparent-lite/1.7.0-SNAPSHOT/odlparent-lite-1.7.0-20160531.105510-131.pom (9 KB at 21.9 KB/sec)
Downloading: https://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/org/opendaylight/odlparent/odlparent-artifacts/1.7.0-SNAPSHOT/maven-metadata.xml
Downloaded: https://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/org/opendaylight/odlparent/odlparent-artifacts/1.7.0-SNAPSHOT/maven-metadata.xml (801 B at 1.9 KB/sec)
Downloading: https://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/org/opendaylight/odlparent/odlparent-artifacts/1.7.0-SNAPSHOT/odlparent-artifacts-1.7.0-20160531.105510-131.pom
Downloaded: https://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/org/opendaylight/odlparent/odlparent-artifacts/1.7.0-SNAPSHOT/odlparent-artifacts-1.7.0-20160531.105510-131.pom (2 KB at 4.1 KB/sec)
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for odl.example:odlexample-api:1.0.0-SNAPSHOT: Failure to find org.opendaylight.mdsal:binding-parent:pom:0.8.2-SNAPSHOT in https://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/ was cached in the local repository, resolution will not be reattempted until the update interval of opendaylight-snapshot has elapsed or updates are forced and 'parent.relativePath' points at no local POM @ line 10, column 11
[FATAL] Non-resolvable parent POM for odl.example:odlexample-impl:1.0.0-SNAPSHOT: Failure to find org.opendaylight.controller:config-parent:pom:0.4.2-SNAPSHOT in https://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/ was cached in the local repository, resolution will not be reattempted until the update interval of opendaylight-snapshot has elapsed or updates are forced and 'parent.relativePath' points at no local POM @ line 12, column 11
[FATAL] Non-resolvable parent POM for odl.example:odlexample-karaf:1.0.0-SNAPSHOT: Failure to find org.opendaylight.controller:karaf-parent:pom:1.6.2-SNAPSHOT in https://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/ was cached in the local repository, resolution will not be reattempted until the update interval of opendaylight-snapshot has elapsed or updates are forced and 'parent.relativePath' points at no local POM @ line 9, column 11
[FATAL] Non-resolvable parent POM for odl.example:odlexample-features:1.0.0-SNAPSHOT: Failure to find org.opendaylight.odlparent:features-parent:pom:1.6.2-SNAPSHOT in https://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/ was cached in the local repository, resolution will not be reattempted until the update interval of opendaylight-snapshot has elapsed or updates are forced and 'parent.relativePath' points at no local POM @ line 10, column 11
[FATAL] Non-resolvable parent POM for odl.example:odlexample-artifacts:1.0.0-SNAPSHOT: Failure to find org.opendaylight.odlparent:odlparent-lite:pom:1.6.2-SNAPSHOT in https://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/ was cached in the local repository, resolution will not be reattempted until the update interval of opendaylight-snapshot has elapsed or updates are forced and 'parent.relativePath' points at no local POM @ line 14, column 11
[FATAL] Non-resolvable parent POM for odl.example:odlexample-it:1.0.0-SNAPSHOT: Failure to find org.opendaylight.controller:mdsal-it-parent:pom:1.3.2-SNAPSHOT in https://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/ was cached in the local repository, resolution will not be reattempted until the update interval of opendaylight-snapshot has elapsed or updates are forced and 'parent.relativePath' points at no local POM @ line 12, column 11
 @ 
[ERROR] The build could not read 6 projects -> [Help 1]
[ERROR]  
[ERROR]   The project odl.example:odlexample-api:1.0.0-SNAPSHOT (/home/ermin/Desktop/odlexample/api/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for odl.example:odlexample-api:1.0.0-SNAPSHOT: Failure to find org.opendaylight.mdsal:binding-parent:pom:0.8.2-SNAPSHOT in https://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/ was cached in the local repository, resolution will not be reattempted until the update interval of opendaylight-snapshot has elapsed or updates are forced and 'parent.relativePath' points at no local POM @ line 10, column 11 -> [Help 2]
[ERROR]  
[ERROR]   The project odl.example:odlexample-impl:1.0.0-SNAPSHOT (/home/ermin/Desktop/odlexample/impl/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for odl.example:odlexample-impl:1.0.0-SNAPSHOT: Failure to find org.opendaylight.controller:config-parent:pom:0.4.2-SNAPSHOT in https://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/ was cached in the local repository, resolution will not be reattempted until the update interval of opendaylight-snapshot has elapsed or updates are forced and 'parent.relativePath' points at no local POM @ line 12, column 11 -> [Help 2]
[ERROR]  
[ERROR]   The project odl.example:odlexample-karaf:1.0.0-SNAPSHOT (/home/ermin/Desktop/odlexample/karaf/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for odl.example:odlexample-karaf:1.0.0-SNAPSHOT: Failure to find org.opendaylight.controller:karaf-parent:pom:1.6.2-SNAPSHOT in https://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/ was cached in the local repository, resolution will not be reattempted until the update interval of opendaylight-snapshot has elapsed or updates are forced and 'parent.relativePath' points at no local POM @ line 9, column 11 -> [Help 2]
[ERROR]  
[ERROR]   The project odl.example:odlexample-features:1.0.0-SNAPSHOT (/home/ermin/Desktop/odlexample/features/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for odl.example:odlexample-features:1.0.0-SNAPSHOT: Failure to find org.opendaylight.odlparent:features-parent:pom:1.6.2-SNAPSHOT in https://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/ was cached in the local repository, resolution will not be reattempted until the update interval of opendaylight-snapshot has elapsed or updates are forced and 'parent.relativePath' points at no local POM @ line 10, column 11 -> [Help 2]
[ERROR]  
[ERROR]   The project odl.example:odlexample-artifacts:1.0.0-SNAPSHOT (/home/ermin/Desktop/odlexample/artifacts/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for odl.example:odlexample-artifacts:1.0.0-SNAPSHOT: Failure to find org.opendaylight.odlparent:odlparent-lite:pom:1.6.2-SNAPSHOT in https://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/ was cached in the local repository, resolution will not be reattempted until the update interval of opendaylight-snapshot has elapsed or updates are forced and 'parent.relativePath' points at no local POM @ line 14, column 11 -> [Help 2]
[ERROR]  
[ERROR]   The project odl.example:odlexample-it:1.0.0-SNAPSHOT (/home/ermin/Desktop/odlexample/it/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for odl.example:odlexample-it:1.0.0-SNAPSHOT: Failure to find org.opendaylight.controller:mdsal-it-parent:pom:1.3.2-SNAPSHOT in https://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/ was cached in the local repository, resolution will not be reattempted until the update interval of opendaylight-snapshot has elapsed or updates are forced and 'parent.relativePath' points at no local POM @ line 12, column 11 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by geopet85** [comment]
Just to be sure, have you configured the settings.xml for Maven as specified [here](https://wiki.opendaylight.org/view/GettingStarted:Development_Environment_Setup)? 

Otherwise they might have deleted the defined snapshot artifacts. I will check it in a clean machine.

**Comment by ermin-sakic** [comment]
Hey George, yes I did!

**Comment by geopet85** [comment]
Updated to next snapshot version, can you `git pull` and try again building?

**Comment by ermin-sakic** [comment]
Looks fine, thanks!

**Comment by miladghaznavi** [comment]
I have the same issue. I clone berilluym branch, and I have settings.xml under .m2 folder. However, when I run the following commands, I get the errors below.

    # export MAVEN_OPTS="-Xmx1024m"
    # export M3_HOME=/usr/share/maven3
    # export M3=$M3_HOME/bin
    # mvn clean install –DskipTests
    [INFO] Scanning for projects...
    [ERROR]
    [ERROR] Some problems were encountered while processing the POMs 
    [FATAL] Non-resolvable parent POM for org.opendaylight.sfc:sfc-parent:0.2.5-SNAPSHOT: Could not find artifact org.opendaylight.odlparent:odlparent:pom:1.6.5-SNAPSHOT and 'parent.relativePath' points at no local POM @ line 9, column 13
    @[ERROR] The build could not read 1 project -> [Help 1]
    [ERROR]
    [ERROR]   The project org.opendaylight.sfc:sfc-parent:0.2.5-SNAPSHOT (/home/odl/sfc/pom.xml) has 1 error
    [ERROR]     Non-resolvable parent POM for org.opendaylight.sfc:sfc-parent:0.2.5-SNAPSHOT: Could not find artifact org.opendaylight.odlparent:odlparent:pom:1.6.5-SNAPSHOT and 'parent.relativePath' points at no local POM @ line 9, column 13 -> [Help 2]
    [ERROR] 
    [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
    [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    [ERROR]
    [ERROR] For more information about the errors and possible solutions, please read the following articles:
    [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
    [ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by geopet85** [comment]
Is this an error from this repository? I suppose not, because i don't include any dependencies on sfc module.

On your issue, you have to fix the version to use only SR, not SNAPSHOT (which probably don't exist any more).
